apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dockerjan.fullname" . }}-config
data:
  APP_ENV: {{ .Values.app.env | quote }}
  APP_NAME: {{ .Values.app.name | quote }}
  APP_VERSION: {{ .Chart.AppVersion | quote }}
